name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint:compile
      - run: npm run lint:scripts
      - run: npm run lint:styles
      - uses: actions/cache@v2.1.0
        with:
          path: |
            ~/.npm
            ~/.next/cache
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
